package com.vieira.pluto.enums;

public enum PROPERTY {
    CLIENTE_EDITAR,
    FUNCIONARIO_EDITAR,
    FABRICANTE_EDITAR,
    EMPRESA_EDITAR,
    USUARIO_EDITAR,
    PRODUTO_EDITAR,
    SERVICO_EDITAR,
    MODELO_VEICULO_EDITAR,
    COR_EDITAR,
    FORMA_PAGAMENTO_EDITAR
}
